# -*- coding: utf-8 -*-
"""seti_2_units.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QsmLkMoogazYpDs_e_U7Me4vS-r11UOU
"""

!pip install blimpy



"""Reference- https://github.com/UCBerkeleySETI/breakthrough/blob/master/GBT/filterbank_tutorial/Filterbank%20Tutorial%20(public).ipynb"""

import astropy

import numpy as np
import blimpy

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt

from blimpy import Waterfall

fil = Waterfall('blc04_guppi_57563_69862_HIP35136_0011.gpuspec.0002.fil')

fil.info()

fil.plot_spectrum()

freq= fil.freqs
freq

dir(Waterfall)

[attr for attr in dir(fil) if not attr.startswith("__")]

data = fil.data

data[10]

data.shape

"""Import the read_header to modify or read the fil header, better than fil.info()"""

from blimpy.io.sigproc import read_header

from astropy import units as u
from astropy.time import Time
from astropy.coordinates import EarthLocation, SkyCoord, AltAz

"""   
   Correction
          
    RA/Dec + observer's location + time

          ↓



        Alt/Az

          ↓
          
      Aim telescope

"""

GreenBank = EarthLocation(lat=38.4322*u.deg, lon=-79.8398*u.deg) #according to telescope location
MJD = read_header('blc04_guppi_57563_69862_HIP35136_0011.gpuspec.0002.fil')['tstart']
ra = read_header('blc04_guppi_57563_69862_HIP35136_0011.gpuspec.0002.fil')['src_raj']
dec = read_header('blc04_guppi_57563_69862_HIP35136_0011.gpuspec.0002.fil')['src_dej']
target = SkyCoord(ra, dec)
altaz = target.transform_to(AltAz(location=GreenBank, obstime=Time(MJD, format='mjd')))

altaz

altaz.alt, altaz.az

altazdict = { 'alt' : altaz.alt.degree, 'az' : altaz.az.degree }

altazdict

